# name of workflow
name: Hello

# run on trigger
# Deployment fron Automatic Triggers
on:
  push:
    branches: [mian]
    paths:
      - "**.html"

jobs:
  # it is the job name 
  greet:
  # run on is the github runner or server used to run jobs
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "hello from Devansh!!!"
    
      - name: say hello to server / runner user
        run: echo "Hllo $USER"

      - name: usage
        run: df -h

  details:
    runs-on: ubuntu-latest

    steps:
      - name: show the version of python or docker
        run: python --version && docker --version
  
